site_name: LongBarcodeQC
site_url: https://goodez.github.io/LongBarcodeQC/
repo_url: https://github.com/goodez/LongBarcodeQC
edit_uri: edit/main/docs/

theme:
  name: readthedocs
  logo: assets/icon.png

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quickstart: getting-started/quickstart.md
  - Usage:
      - CLI Reference: usage/cli.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
