[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "LongBarcodeQC"
version = "1.0.1"
description = "Analyze long-read barcodes and generate a summary report"
authors = [
    {name="Zach Goode", email="goodez@ohsu.edu"}
]
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
keywords = [
    "bioinformatics",
    "nanopore",
    "long-read sequencing",
    "barcode",
    "quality control",
    "plasmid",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Environment :: Console",
]
dependencies = [
    "pandas >= 2.1.1",
    "parasail >= 1.3.4",
    "matplotlib >= 3.8.4",
    "jinja2 >= 3.1.4",
    "seaborn >= 0.13.2",
    "pyarrow >= 14.0",
    "tqdm >= 4.66",
    "cutadapt >= 5.2"
]

readme = "README.md"

[project.urls]
Homepage = "https://github.com/ArpiarSaundersLab/LongBarcodeQC"
Documentation = "https://arpiarsaunderslab.github.io/LongBarcodeQC/"
Repository = "https://github.com/ArpiarSaundersLab/LongBarcodeQC"
Issues = "https://github.com/ArpiarSaundersLab/LongBarcodeQC/issues"

[tool.setuptools]
packages = ["longbarcodeqc"]

[project.scripts]
lbqc = "longbarcodeqc.main:main"

[tool.setuptools.package-data]
"longbarcodeqc" = ["plasmids/**", "template/**", "barcodes/**"]
